In [20]:
#cleaning of dataset
import pandas as pd
dataset = pd.read_csv(r"C:\Users\61005\OneDrive\Desktop\jupyter notebook\Netflix Dataset.csv")
print(dataset.head())

  Show_Id Category  Title           Director  \
0      s1  TV Show     3%                NaN
1      s2    Movie  07:19  Jorge Michel Grau
2      s3    Movie  23:59       Gilbert Chan
3      s4    Movie      9        Shane Acker
4      s5    Movie     21     Robert Luketic

                                                Cast        Country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States

        Release_Date Rating   Duration  \
0    August 14, 2020  TV-MA  4 Seasons
1  December 23, 2016  TV-MA     93 min
2  December 20, 2018      R     78 min
3  November 16, 2017  PG-13     80 min
4    January 1, 2020  PG-13    123 min

                                                Type  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...
1                       Dramas, International Movies
2                Horror Movies, International Movies
3  Action & Adventure, Independent Movies, Sci-Fi...
4                                             Dramas

                                         Description
0  In a future where the elite inhabit an island ...
1  After a devastating earthquake hits Mexico Cit...
2  When an army recruit is found dead, his fellow...
3  In a postapocalyptic world, rag-doll robots hi...
4  A brilliant group of students become card-coun...

In [21]:
dataset.head()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [23]:

dataset.describe(include="all")

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
count,7789,7789,7789,5401,7071,7282,7779,7782,7789,7789,7789
unique,7787,2,7787,4050,6831,681,1565,14,216,492,7769
top,s684,Movie,Backfire,"Raúl Campos, Jan Suter",David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,Documentaries,Multiple women report their husbands as missin...
freq,2,5379,2,18,18,2556,118,2865,1608,334,3

In [22]:

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7789 entries, 0 to 7788
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_Id       7789 non-null   object
 1   Category      7789 non-null   object
 2   Title         7789 non-null   object
 3   Director      5401 non-null   object
 4   Cast          7071 non-null   object
 5   Country       7282 non-null   object
 6   Release_Date  7779 non-null   object
 7   Rating        7782 non-null   object
 8   Duration      7789 non-null   object
 9   Type          7789 non-null   object
 10  Description   7789 non-null   object
dtypes: object(11)
memory usage: 669.5+ KB

In [23]:
#dataset  missing value handling 
dataset["Director"] = dataset["Director"].fillna("Unknown")
dataset["Cast"] = dataset["Cast"].fillna("Unknown")
dataset["Country"] = dataset["Country"].fillna("Unknown")
dataset["Rating"] = dataset["Rating"].fillna("Unknown")
dataset["Release_Date"] = dataset["Release_Date"].fillna("Unknown")

In [24]:
dataset.isnull().sum()

Show_Id         0
Category        0
Title           0
Director        0
Cast            0
Country         0
Release_Date    0
Rating          0
Duration        0
Type            0
Description     0
dtype: int64

In [35]:
#handling dulicated value
dataset.drop_duplicates(inplace=True)

In [25]:
dataset.duplicated().sum()

np.int64(2)

In [26]:
dataset.dtypes

Show_Id         object
Category        object
Title           object
Director        object
Cast            object
Country         object
Release_Date    object
Rating          object
Duration        object
Type            object
Description     object
dtype: object

In [39]:
dataset['Release_Date'] = pd.to_datetime(dataset['Release_Date'], errors='coerce')

In [27]:
dataset.dtypes

Show_Id         object
Category        object
Title           object
Director        object
Cast            object
Country         object
Release_Date    object
Rating          object
Duration        object
Type            object
Description     object
dtype: object

In [28]:
dataset['Category'].unique()

array(['TV Show', 'Movie'], dtype=object)

In [29]:
dataset['Rating'].unique()

array(['TV-MA', 'R', 'PG-13', 'TV-14', 'TV-PG', 'NR', 'TV-G', 'TV-Y',
       'Unknown', 'TV-Y7', 'PG', 'G', 'NC-17', 'TV-Y7-FV', 'UR'],
      dtype=object)

In [30]:
dataset['Type'].unique()

array(['International TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Dramas, International Movies',
       'Horror Movies, International Movies',
       'Action & Adventure, Independent Movies, Sci-Fi & Fantasy',
       'Dramas', 'International TV Shows, TV Dramas, TV Mysteries',
       'Horror Movies, International Movies, Thrillers',
       'Dramas, Thrillers',
       'Crime TV Shows, International TV Shows, TV Dramas',
       'Crime TV Shows, Docuseries, International TV Shows',
       'Documentaries, International Movies, Sports Movies',
       'Independent Movies, Sci-Fi & Fantasy, Thrillers',
       'Dramas, International Movies, Thrillers',
       'International TV Shows, TV Dramas',
       'Comedies, Dramas, Independent Movies', 'Sports Movies',
       'Dramas, Independent Movies, International Movies',
       'Action & Adventure, Dramas, International Movies',
       'Anime Series, International TV Shows', 'Documentaries',
       'Reality TV', 'Documentaries, International Movies', 'TV Comedies',
       'Dramas, International Movies, Romantic Movies', 'Comedies',
       'Comedies, Romantic Movies', 'Documentaries, Sports Movies',
       'Comedies, Dramas, International Movies',
       'International TV Shows, Romantic TV Shows, TV Comedies',
       'Comedies, International Movies',
       'Action & Adventure, Sci-Fi & Fantasy', 'Dramas, Romantic Movies',
       'Dramas, Romantic Movies, Sports Movies',
       'Comedies, International Movies, Romantic Movies',
       'Action & Adventure',
       'International TV Shows, Romantic TV Shows, TV Dramas',
       'Docuseries, Science & Nature TV',
       'Dramas, International Movies, Sports Movies', 'Movies',
       'British TV Shows, International TV Shows, Reality TV',
       'Dramas, Independent Movies, Sports Movies',
       'International TV Shows, Korean TV Shows, Romantic TV Shows',
       'Horror Movies, Independent Movies, Thrillers',
       'Crime TV Shows, TV Dramas, TV Mysteries',
       'Crime TV Shows, Docuseries', 'Horror Movies, Thrillers',
       'Action & Adventure, International Movies',
       'Horror Movies, Independent Movies',
       'Documentaries, Music & Musicals',
       'International Movies, Music & Musicals', 'Sci-Fi & Fantasy',
       'Dramas, Independent Movies', 'British TV Shows, Reality TV',
       'Action & Adventure, Comedies, International Movies',
       'Comedies, Dramas', 'Dramas, LGBTQ Movies',
       'Documentaries, Faith & Spirituality',
       'Action & Adventure, Comedies',
       "Kids' TV, TV Action & Adventure, TV Sci-Fi & Fantasy",
       'International Movies, Thrillers', "Kids' TV",
       'International TV Shows, Romantic TV Shows, Spanish-Language TV Shows',
       'Children & Family Movies, Comedies', 'Comedies, LGBTQ Movies',
       'Comedies, Dramas, Romantic Movies', 'Action & Adventure, Dramas',
       'Dramas, Independent Movies, Romantic Movies',
       'Comedies, Independent Movies, Thrillers', 'TV Shows',
       'Docuseries', 'Comedies, International Movies, Music & Musicals',
       'Docuseries, International TV Shows, Science & Nature TV',
       'British TV Shows, Docuseries, Science & Nature TV',
       'Children & Family Movies, Dramas, Sports Movies',
       'Children & Family Movies', 'Dramas, Sci-Fi & Fantasy',
       'International TV Shows, TV Comedies, TV Dramas',
       'Action & Adventure, Classic Movies, Dramas',
       'Children & Family Movies, Dramas',
       'Action & Adventure, International Movies, Romantic Movies',
       'Children & Family Movies, Dramas, Romantic Movies',
       'Children & Family Movies, Comedies, Music & Musicals',
       'Classic Movies, Cult Movies, Dramas',
       'Action & Adventure, International Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies', 'Comedies, Horror Movies',
       'Children & Family Movies, Comedies, Romantic Movies',
       'International TV Shows, TV Dramas, TV Horror', 'Thrillers',
       'Stand-Up Comedy & Talk Shows, TV Comedies',
       'International TV Shows, Romantic TV Shows, Teen TV Shows',
       'Crime TV Shows, International TV Shows, Korean TV Shows',
       'Comedies, International Movies, Sports Movies',
       'Dramas, LGBTQ Movies, Romantic Movies', 'Comedies, Cult Movies',
       'Dramas, Independent Movies, LGBTQ Movies',
       'International TV Shows, Reality TV', 'Stand-Up Comedy',
       'Documentaries, LGBTQ Movies',
       "Kids' TV, TV Action & Adventure, TV Comedies",
       'Anime Features, International Movies',
       'Music & Musicals, Romantic Movies', 'Comedies, Music & Musicals',
       'International TV Shows, TV Comedies',
       'International Movies, Romantic Movies',
       'Anime Features, Children & Family Movies, International Movies',
       'British TV Shows, TV Comedies, TV Dramas', 'TV Dramas',
       'Horror Movies',
       'Action & Adventure, Children & Family Movies, Independent Movies',
       'Dramas, International Movies, Music & Musicals',
       'Comedies, International Movies, Sci-Fi & Fantasy',
       'International TV Shows, Korean TV Shows, Stand-Up Comedy & Talk Shows',
       'Docuseries, Science & Nature TV, TV Comedies',
       'Dramas, Sports Movies',
       'Dramas, Music & Musicals, Romantic Movies',
       'Children & Family Movies, Comedies, International Movies',
       'Action & Adventure, Documentaries, International Movies',
       'Comedies, International Movies, Thrillers',
       'Action & Adventure, Dramas, Romantic Movies',
       'Horror Movies, Independent Movies, International Movies',
       'Dramas, Independent Movies, Sci-Fi & Fantasy',
       'International Movies, Sci-Fi & Fantasy',
       'Docuseries, Reality TV, Science & Nature TV',
       'British TV Shows, Docuseries, International TV Shows',
       'Docuseries, International TV Shows',
       'British TV Shows, International TV Shows, TV Comedies',
       'Action & Adventure, Horror Movies',
       'British TV Shows, Reality TV, Romantic TV Shows',
       'Crime TV Shows, International TV Shows, TV Action & Adventure',
       'International TV Shows, Reality TV, Romantic TV Shows',
       'International Movies, Music & Musicals, Romantic Movies',
       'TV Comedies, TV Dramas',
       'Anime Series, Crime TV Shows, International TV Shows',
       "Kids' TV, TV Comedies, TV Dramas",
       'Action & Adventure, Comedies, Dramas',
       'Documentaries, International Movies, Music & Musicals',
       "Kids' TV, TV Comedies",
       'Classic Movies, Dramas, International Movies',
       'Comedies, Independent Movies, International Movies',
       'Classic Movies, Comedies, Dramas',
       'International TV Shows, TV Action & Adventure, TV Mysteries',
       'Comedies, International Movies, LGBTQ Movies',
       'Children & Family Movies, Comedies, Sci-Fi & Fantasy',
       'TV Dramas, Teen TV Shows',
       'Children & Family Movies, Independent Movies',
       'International TV Shows, Spanish-Language TV Shows, TV Comedies',
       'Crime TV Shows, TV Action & Adventure, TV Dramas',
       'Action & Adventure, Anime Features, International Movies',
       'Action & Adventure, Classic Movies, Comedies',
       'Crime TV Shows, TV Dramas',
       'TV Horror, TV Mysteries, TV Thrillers', 'TV Dramas, TV Thrillers',
       'Comedies, Cult Movies, Dramas',
       'Crime TV Shows, TV Comedies, Teen TV Shows',
       'Dramas, Faith & Spirituality', 'Comedies, Dramas, LGBTQ Movies',
       'Action & Adventure, Comedies, Cult Movies',
       'International TV Shows, TV Action & Adventure, TV Comedies',
       'Dramas, Independent Movies, Music & Musicals',
       'International TV Shows, TV Horror, TV Thrillers',
       'International TV Shows, TV Horror, TV Mysteries',
       'International TV Shows, TV Dramas, Teen TV Shows',
       'Anime Series, International TV Shows, Teen TV Shows',
       'Dramas, Sci-Fi & Fantasy, Thrillers',
       'TV Action & Adventure, TV Dramas, TV Mysteries',
       'Crime TV Shows, International TV Shows, TV Comedies',
       'Action & Adventure, Comedies, Sci-Fi & Fantasy',
       "Anime Series, Kids' TV",
       'Crime TV Shows, International TV Shows, Spanish-Language TV Shows',
       'Horror Movies, Sci-Fi & Fantasy, Thrillers',
       'International TV Shows, Korean TV Shows, TV Dramas',
       'Stand-Up Comedy & Talk Shows',
       'International Movies, Sci-Fi & Fantasy, Thrillers',
       'Crime TV Shows, TV Action & Adventure',
       'International TV Shows, Korean TV Shows, TV Action & Adventure',
       'TV Action & Adventure, TV Comedies, TV Horror',
       'International TV Shows, Romantic TV Shows',
       "Crime TV Shows, Kids' TV, TV Comedies",
       'TV Comedies, TV Dramas, Teen TV Shows',
       'Docuseries, International TV Shows, Reality TV',
       "Classic & Cult TV, Kids' TV, TV Action & Adventure",
       'Horror Movies, Sci-Fi & Fantasy',
       'Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Dramas, International Movies, Sci-Fi & Fantasy',
       'Children & Family Movies, Sports Movies',
       'Dramas, Independent Movies, Thrillers',
       'Independent Movies, International Movies, Thrillers',
       'British TV Shows, TV Comedies',
       'International TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Action & Adventure, Comedies, Independent Movies',
       'International TV Shows, TV Action & Adventure, TV Dramas',
       'Children & Family Movies, Music & Musicals', 'Music & Musicals',
       'Action & Adventure, International Movies, Music & Musicals',
       'Comedies, Sports Movies', 'Classic Movies, Thrillers',
       'Docuseries, Reality TV', 'Crime TV Shows, TV Dramas, TV Horror',
       'Crime TV Shows, TV Comedies, TV Dramas',
       'British TV Shows, Docuseries, Reality TV',
       'Reality TV, Science & Nature TV, TV Action & Adventure',
       'Children & Family Movies, Documentaries, International Movies',
       'Crime TV Shows, Romantic TV Shows, TV Dramas',
       'British TV Shows, Docuseries',
       'Documentaries, LGBTQ Movies, Music & Musicals',
       'Romantic TV Shows, TV Dramas', 'Independent Movies, Thrillers',
       'International TV Shows, TV Action & Adventure, TV Horror',
       'Children & Family Movies, Documentaries, Sports Movies',
       'Stand-Up Comedy & Talk Shows, TV Mysteries, TV Sci-Fi & Fantasy',
       'International TV Shows, Reality TV, TV Comedies',
       'Dramas, International Movies, LGBTQ Movies',
       'Action & Adventure, Dramas, Independent Movies',
       'British TV Shows, International TV Shows, TV Dramas',
       'TV Action & Adventure, TV Dramas, TV Sci-Fi & Fantasy',
       'TV Action & Adventure, TV Dramas, TV Horror',
       'Action & Adventure, Anime Features, Sci-Fi & Fantasy',
       'Anime Series', 'TV Dramas, TV Mysteries, TV Thrillers',
       'Music & Musicals, Stand-Up Comedy',
       'Docuseries, International TV Shows, Spanish-Language TV Shows',
       'Crime TV Shows, International TV Shows, Reality TV',
       "British TV Shows, Kids' TV",
       'Docuseries, Spanish-Language TV Shows',
       'Crime TV Shows, TV Dramas, TV Thrillers',
       'Documentaries, International Movies, LGBTQ Movies',
       'British TV Shows, Crime TV Shows, International TV Shows',
       'Action & Adventure, Independent Movies',
       'Classic Movies, Dramas, Romantic Movies',
       'Crime TV Shows, Romantic TV Shows, Spanish-Language TV Shows',
       'Children & Family Movies, Comedies, Dramas',
       'Cult Movies, Horror Movies', "Kids' TV, TV Thrillers",
       'Classic Movies, Cult Movies, Horror Movies',
       'Anime Series, Crime TV Shows, TV Thrillers',
       'Anime Series, TV Horror, TV Thrillers', 'Classic Movies, Dramas',
       'British TV Shows, Crime TV Shows, Docuseries',
       'Action & Adventure, International Movies, Thrillers',
       'Anime Series, Teen TV Shows',
       'Children & Family Movies, Dramas, International Movies',
       'Dramas, Faith & Spirituality, International Movies',
       'TV Horror, TV Mysteries, Teen TV Shows',
       'Children & Family Movies, Classic Movies',
       'TV Dramas, TV Sci-Fi & Fantasy', 'Reality TV, Teen TV Shows',
       'Docuseries, Reality TV, Teen TV Shows',
       'Classic & Cult TV, TV Comedies',
       'International TV Shows, Korean TV Shows, Reality TV',
       'International TV Shows, Stand-Up Comedy & Talk Shows, TV Comedies',
       'British TV Shows, International TV Shows, Romantic TV Shows',
       'International TV Shows, TV Dramas, TV Thrillers',
       'Anime Features', 'TV Horror, TV Mysteries, TV Sci-Fi & Fantasy',
       'Children & Family Movies, Classic Movies, Comedies',
       'Comedies, Faith & Spirituality, Romantic Movies',
       'Classic Movies, Comedies, International Movies',
       'Action & Adventure, Horror Movies, Sci-Fi & Fantasy',
       'Action & Adventure, Classic Movies',
       'TV Dramas, TV Sci-Fi & Fantasy, TV Thrillers',
       'Comedies, Sci-Fi & Fantasy',
       'Action & Adventure, Cult Movies, Dramas',
       'TV Action & Adventure, TV Dramas', "Kids' TV, Korean TV Shows",
       'Action & Adventure, Independent Movies, International Movies',
       'Dramas, Faith & Spirituality, Independent Movies',
       'Docuseries, TV Comedies',
       'Documentaries, Faith & Spirituality, Music & Musicals',
       'Romantic TV Shows, TV Comedies',
       "Kids' TV, Spanish-Language TV Shows",
       "British TV Shows, Kids' TV, TV Thrillers",
       'Action & Adventure, Romantic Movies',
       'British TV Shows, Classic & Cult TV, TV Comedies',
       'Action & Adventure, Horror Movies, International Movies',
       'Children & Family Movies, Documentaries',
       "British TV Shows, Kids' TV, TV Comedies",
       'Horror Movies, Independent Movies, Sci-Fi & Fantasy',
       'TV Sci-Fi & Fantasy, TV Thrillers',
       'Romantic TV Shows, TV Comedies, TV Dramas',
       'Reality TV, Romantic TV Shows',
       'Classic Movies, Dramas, Independent Movies',
       'Romantic TV Shows, TV Dramas, Teen TV Shows',
       'TV Action & Adventure, TV Sci-Fi & Fantasy',
       'British TV Shows, TV Horror, TV Thrillers',
       'International Movies, Sports Movies', 'International Movies',
       'Anime Series, International TV Shows, TV Horror',
       'International TV Shows',
       'Dramas, Music & Musicals, Sports Movies',
       'International TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'Cult Movies, Dramas, International Movies',
       'TV Action & Adventure, TV Comedies, TV Sci-Fi & Fantasy',
       'Reality TV, Science & Nature TV',
       'Action & Adventure, Anime Features, Children & Family Movies',
       "Kids' TV, TV Action & Adventure",
       'Children & Family Movies, Sci-Fi & Fantasy',
       "Crime TV Shows, Kids' TV",
       'International Movies, Music & Musicals, Thrillers',
       'Crime TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       "Classic & Cult TV, Kids' TV, Spanish-Language TV Shows",
       'Romantic TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Action & Adventure, Cult Movies, International Movies',
       'Crime TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Action & Adventure, Children & Family Movies, Dramas',
       'Dramas, Romantic Movies, Sci-Fi & Fantasy',
       'Action & Adventure, Dramas, Sci-Fi & Fantasy',
       'International TV Shows, TV Mysteries, TV Thrillers',
       'Anime Series, International TV Shows, TV Thrillers',
       'Horror Movies, International Movies, Sci-Fi & Fantasy',
       'Comedies, Cult Movies, International Movies',
       'Comedies, Music & Musicals, Romantic Movies',
       'Children & Family Movies, Comedies, Faith & Spirituality',
       'Crime TV Shows, Docuseries, TV Mysteries',
       'Crime TV Shows, Docuseries, Science & Nature TV',
       'British TV Shows, Crime TV Shows, TV Dramas',
       'Classic Movies, Comedies, Cult Movies',
       'International Movies, Romantic Movies, Thrillers',
       'Classic Movies, Dramas, Music & Musicals',
       'Cult Movies, Horror Movies, Thrillers',
       'Anime Features, Romantic Movies',
       'Comedies, Dramas, Music & Musicals',
       'Anime Features, International Movies, Romantic Movies',
       'Documentaries, Faith & Spirituality, International Movies',
       'Action & Adventure, Classic Movies, Sci-Fi & Fantasy',
       'International TV Shows, Stand-Up Comedy & Talk Shows',
       "British TV Shows, Kids' TV, TV Dramas",
       'Classic & Cult TV, TV Action & Adventure, TV Horror',
       'Children & Family Movies, Dramas, Faith & Spirituality',
       'TV Action & Adventure, TV Comedies',
       'Action & Adventure, Anime Features, Horror Movies',
       'Crime TV Shows, International TV Shows, Romantic TV Shows',
       'Classic Movies, Comedies, Music & Musicals',
       'Comedies, Horror Movies, International Movies',
       "Kids' TV, Spanish-Language TV Shows, Teen TV Shows",
       'Independent Movies',
       'Crime TV Shows, International TV Shows, TV Mysteries',
       'Action & Adventure, Thrillers',
       "Kids' TV, TV Dramas, Teen TV Shows",
       'Anime Series, Crime TV Shows', "Kids' TV, TV Dramas",
       'Crime TV Shows, TV Action & Adventure, TV Comedies',
       'TV Comedies, Teen TV Shows',
       'Reality TV, TV Horror, TV Thrillers',
       'Documentaries, Horror Movies',
       'Classic & Cult TV, TV Horror, TV Mysteries',
       'Action & Adventure, Cult Movies, Sci-Fi & Fantasy',
       'Anime Series, International TV Shows, Romantic TV Shows',
       'Action & Adventure, Comedies, Romantic Movies',
       'Comedies, Dramas, Faith & Spirituality',
       'Comedies, Faith & Spirituality, International Movies',
       'Romantic Movies', 'Dramas, Horror Movies, Sci-Fi & Fantasy',
       'International TV Shows, Korean TV Shows, TV Comedies',
       'Comedies, Independent Movies, LGBTQ Movies',
       'TV Comedies, TV Dramas, TV Sci-Fi & Fantasy',
       'Dramas, Music & Musicals',
       'Dramas, Faith & Spirituality, Romantic Movies',
       'International TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Reality TV, TV Comedies',
       "Docuseries, Kids' TV, Science & Nature TV",
       'Action & Adventure, Sci-Fi & Fantasy, Thrillers',
       'Action & Adventure, Children & Family Movies, Sci-Fi & Fantasy',
       'Action & Adventure, Children & Family Movies, Classic Movies',
       'Horror Movies, International Movies, Romantic Movies',
       'TV Action & Adventure', 'TV Comedies, TV Dramas, TV Horror',
       'British TV Shows, International TV Shows, Stand-Up Comedy & Talk Shows',
       'Dramas, Music & Musicals, Sci-Fi & Fantasy',
       'Spanish-Language TV Shows, TV Dramas',
       'Documentaries, Stand-Up Comedy',
       'Classic & Cult TV, TV Action & Adventure, TV Dramas',
       'British TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Anime Features, Music & Musicals',
       'International TV Shows, TV Comedies, TV Sci-Fi & Fantasy',
       'Comedies, Independent Movies, Romantic Movies',
       'Comedies, Cult Movies, Horror Movies',
       'Comedies, Cult Movies, Sports Movies',
       'Classic Movies, Documentaries', 'Sci-Fi & Fantasy, Thrillers',
       'Classic & Cult TV, Crime TV Shows, International TV Shows',
       "Kids' TV, Korean TV Shows, TV Comedies",
       'British TV Shows, Romantic TV Shows, TV Dramas',
       'Action & Adventure, Faith & Spirituality, Sci-Fi & Fantasy',
       'TV Dramas, TV Sci-Fi & Fantasy, Teen TV Shows',
       'Action & Adventure, Children & Family Movies',
       'Comedies, Horror Movies, Independent Movies',
       'Action & Adventure, Classic Movies, Cult Movies',
       'TV Dramas, TV Horror, TV Mysteries',
       'International Movies, Romantic Movies, Sci-Fi & Fantasy',
       'Anime Series, Romantic TV Shows, Teen TV Shows',
       'TV Action & Adventure, TV Horror, TV Sci-Fi & Fantasy',
       'Anime Features, Music & Musicals, Sci-Fi & Fantasy',

In [31]:
dataset['Duration'].unique()[:20]

array(['4 Seasons', '93 min', '78 min', '80 min', '123 min', '1 Season',
       '95 min', '119 min', '118 min', '143 min', '103 min', '89 min',
       '91 min', '149 min', '144 min', '124 min', '87 min', '110 min',
       '128 min', '117 min'], dtype=object)

In [32]:
#checking for extra space
dataset.columns = dataset.columns.str.strip()

for col in dataset.select_dtypes(include='object').columns:
    dataset[col] = dataset[col].str.strip()

In [33]:
dataset.head()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,Unknown,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [34]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7789 entries, 0 to 7788
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_Id       7789 non-null   object
 1   Category      7789 non-null   object
 2   Title         7789 non-null   object
 3   Director      7789 non-null   object
 4   Cast          7789 non-null   object
 5   Country       7789 non-null   object
 6   Release_Date  7789 non-null   object
 7   Rating        7789 non-null   object
 8   Duration      7789 non-null   object
 9   Type          7789 non-null   object
 10  Description   7789 non-null   object
dtypes: object(11)
memory usage: 669.5+ KB

In [54]:
# handling nat values
dataset[dataset['Release_Date'].isnull()]

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
258,s259,TV Show,A Young Doctor's Notebook and Other Stories,Unknown,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaT,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
284,s285,TV Show,Abnormal Summit,"Jung-ah Im, Seung-uk Jo","Hyun-moo Jun, Si-kyung Sung, Se-yoon Yoo",South Korea,NaT,TV-PG,2 Seasons,"International TV Shows, Korean TV Shows, Stand...","Led by a trio of Korean celebs, a multinationa..."
549,s550,TV Show,Anthony Bourdain: Parts Unknown,Unknown,Anthony Bourdain,United States,NaT,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
556,s557,TV Show,忍者ハットリくん,Unknown,Unknown,Japan,NaT,TV-Y7,2 Seasons,"Anime Series, Kids' TV","Hailing from the mountains of Iga, Kanzo Hatto..."
690,s691,TV Show,Bad Education,Unknown,"Jack Whitehall, Mathew Horne, Sarah Solemani, ...",United Kingdom,NaT,TV-MA,3 Seasons,"British TV Shows, TV Comedies","A history teacher at the posh Abbey Grove, Alf..."
...,...,...,...,...,...,...,...,...,...,...,...
6952,s6951,TV Show,The Tudors,Unknown,"Jonathan Rhys Meyers, Henry Cavill, James Frai...","Ireland, Canada, United States, United Kingdom",NaT,TV-MA,4 Seasons,TV Dramas,All the splendor and scandal of England's 16th...
6998,s6997,TV Show,The West Wing,Unknown,"Martin Sheen, Rob Lowe, Allison Janney, John S...",United States,NaT,TV-14,7 Seasons,TV Dramas,This powerful political epic chronicles the tr...
7448,s7447,TV Show,Vroomiz,Unknown,"Joon-seok Song, Jeong-hwa Yang, Sang-hyun Um, ...",South Korea,NaT,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows","For these half-car, half-animal friends, each ..."
7524,s7523,TV Show,Weird Wonders of the World,Unknown,Chris Packham,United Kingdom,NaT,TV-PG,2 Seasons,"British TV Shows, Docuseries, Science & Nature TV",From animal oddities and bizarre science to me...
7655,s7654,TV Show,Women Behind Bars,Unknown,Unknown,United States,NaT,TV-14,3 Seasons,"Crime TV Shows, Docuseries",This reality series recounts true stories of w...

In [35]:
# removing nat values
dataset.dropna(subset=['Release_Date'], inplace=True)

In [57]:
dataset.reset_index(drop=True, inplace=True)

In [36]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7789 entries, 0 to 7788
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_Id       7789 non-null   object
 1   Category      7789 non-null   object
 2   Title         7789 non-null   object
 3   Director      7789 non-null   object
 4   Cast          7789 non-null   object
 5   Country       7789 non-null   object
 6   Release_Date  7789 non-null   object
 7   Rating        7789 non-null   object
 8   Duration      7789 non-null   object
 9   Type          7789 non-null   object
 10  Description   7789 non-null   object
dtypes: object(11)
memory usage: 669.5+ KB

In [37]:
dataset.isnull().sum()

Show_Id         0
Category        0
Title           0
Director        0
Cast            0
Country         0
Release_Date    0
Rating          0
Duration        0
Type            0
Description     0
dtype: int64

In [38]:
dataset.describe(include='all')

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
count,7789,7789,7789,7789,7789,7789,7789,7789,7789,7789,7789
unique,7787,2,7786,4051,6832,682,1513,15,216,492,7769
top,s684,Movie,Consequences,Unknown,Unknown,United States,"January 1, 2020",TV-MA,1 Season,Documentaries,Multiple women report their husbands as missin...
freq,2,5379,2,2388,718,2556,119,2865,1608,334,3

In [39]:
# featuring of dataset using TF-IDF/countvectorize
import pandas as pd
dataset = pd.read_csv(r"C:\Users\61005\OneDrive\Desktop\jupyter notebook\Netflix Dataset.csv")
dataset[['Title', 'Category', 'Director', 'Cast', 'Type', 'Description']].head()

,Title,Category,Director,Cast,Type,Description
0,3%,TV Show,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...","International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,07:19,Movie,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...","Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,23:59,Movie,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...","Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,9,Movie,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...","Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,21,Movie,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",Dramas,A brilliant group of students become card-coun...

In [40]:
dataset['tags'] = (
    dataset['Category'].astype(str) + ' ' +
    dataset['Director'].astype(str) + ' ' +
    dataset['Cast'].astype(str) + ' ' +
    dataset['Type'].astype(str) + ' ' +
    dataset['Description'].astype(str)
)

In [41]:
dataset[['Title', 'tags']].head()

   Title                                               tags
0     3%  TV Show nan João Miguel, Bianca Comparato, Mic...
1  07:19  Movie Jorge Michel Grau Demián Bichir, Héctor ...
2  23:59  Movie Gilbert Chan Tedd Chan, Stella Chung, He...
3      9  Movie Shane Acker Elijah Wood, John C. Reilly,...
4     21  Movie Robert Luketic Jim Sturgess, Kevin Space...

In [42]:
dataset[['Title', 'tags']].head().values

array([['3%',
        'TV Show nan João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi International TV Shows, TV Dramas, TV Sci-Fi & Fantasy In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor.'],
       ['07:19',
        'Movie Jorge Michel Grau Demián Bichir, Héctor Bonilla, Oscar Serrano, Azalia Ortiz, Octavio Michel, Carmen Beato Dramas, International Movies After a devastating earthquake hits Mexico City, trapped survivors from all walks of life wait to be rescued while trying desperately to stay alive.'],
       ['23:59',
        "Movie Gilbert Chan Tedd Chan, Stella Chung, Henley Hii, Lawrence Koh, Tommy Kuan, Josh Lai, Mark Lee, Susan Leong, Benjamin Lim Horror Movies, International Movies When an army recruit is found dead, his fellow soldiers are forced to confront a terrifying secret that's haunting their jungle island training camp."],
       ['9',
        'Movie Shane Acker Elijah Wood, John C. Reilly, Jennifer Connelly, Christopher Plummer, Crispin Glover, Martin Landau, Fred Tatasciore, Alan Oppenheimer, Tom Kane Action & Adventure, Independent Movies, Sci-Fi & Fantasy In a postapocalyptic world, rag-doll robots hide in fear from dangerous machines out to exterminate them, until a brave newcomer joins the group.'],
       ['21',
        'Movie Robert Luketic Jim Sturgess, Kevin Spacey, Kate Bosworth, Aaron Yoo, Liza Lapira, Jacob Pitts, Laurence Fishburne, Jack McGee, Josh Gad, Sam Golzari, Helen Carey, Jack Gilpin Dramas A brilliant group of students become card-counting experts with the intent of swindling millions out of Las Vegas casinos by playing blackjack.']],
      dtype=object)

In [43]:
# now applying countvectorize from skitlearn (for featuring our  data )
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(dataset['tags']).toarray()
vectors.shape

(7789, 5000)

In [65]:
# applying pca for our recommendation system
from sklearn.decomposition import PCA
pca = PCA(n_components=1000)
vectors_pca = pca.fit_transform(vectors).astype("float32")
vectors_pca.shape

(7789, 1000)

In [45]:
# checking variance from our original data and  are accurate approx 74%
pca.explained_variance_ratio_.sum()

np.float64(0.7450921439822609)

In [46]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [47]:
# prepration of train_data before training the model

type_sets = dataset["Type"].apply(
    lambda x: set(i.strip() for i in x.split(","))
)

print(type_sets.head())

0    {TV Sci-Fi & Fantasy, International TV Shows, ...
1                       {Dramas, International Movies}
2                {International Movies, Horror Movies}
3    {Action & Adventure, Sci-Fi & Fantasy, Indepen...
4                                             {Dramas}
Name: Type, dtype: object

In [131]:
# Creating pairs and calculating similarity

import random
import torch
import torch.nn.functional as F

pairs = []
similarities = []

num_pairs = 30000


for _ in range(num_pairs):

    # Selecting two random movies
    i = random.randint(0, len(vectors_pca) - 1)
    j = random.randint(0, len(vectors_pca) - 1)

    # Don't compare a movie with itself
    while i == j:
        j = random.randint(0, len(vectors_pca) - 1)

    # Getting movie PCA vectors
    movie_a = torch.tensor(
        vectors_pca[i],
        dtype=torch.float32
    )

    movie_b = torch.tensor(
        vectors_pca[j],
        dtype=torch.float32
    )

    # Calculating cosine similarity
    similarity = F.cosine_similarity(
        movie_a.unsqueeze(0),
        movie_b.unsqueeze(0)
    ).item()

    # Storing movie pair
    pairs.append((i, j))

    # Storing similarity
    similarities.append(similarity)


print("Total pairs:", len(pairs))
print("Highest similarity:", max(similarities))
print("Lowest similarity:", min(similarities))

Total pairs: 30000
Highest similarity: 0.7532973289489746
Lowest similarity: -0.48957887291908264

In [132]:
# Combining pairs and similarities

combined = list(
    zip(pairs, similarities)
)


# Sorting by cosine similarity

combined.sort(
    key=lambda x: x[1],
    reverse=True
)


print("Highest similarity:", combined[0][1])
print("Lowest similarity:", combined[-1][1])

Highest similarity: 0.7532973289489746
Lowest similarity: -0.48957887291908264

In [133]:
# Creating balanced pairs and labels

pairs = []
labels = []

num_balanced = 5000


# Creating similar pairs

for pair, similarity in combined[:num_balanced]:

    pairs.append(pair)
    labels.append(1)


# Creating dissimilar pairs

for pair, similarity in combined[-num_balanced:]:

    pairs.append(pair)
    labels.append(0)


print("Total pairs:", len(pairs))
print("Similar pairs:", labels.count(1))
print("Dissimilar pairs:", labels.count(0))

Total pairs: 10000
Similar pairs: 5000
Dissimilar pairs: 5000

In [134]:
# Train and testing data split

from sklearn.model_selection import train_test_split

train_pairs, test_pairs, train_labels, test_labels = train_test_split(
    pairs,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)


print("Training pairs:", len(train_pairs))
print("Testing pairs:", len(test_pairs))

print("\nTraining similar:", train_labels.count(1))
print("Training dissimilar:", train_labels.count(0))

print("\nTesting similar:", test_labels.count(1))
print("Testing dissimilar:", test_labels.count(0))

Training pairs: 8000
Testing pairs: 2000

Training similar: 4000
Training dissimilar: 4000

Testing similar: 1000
Testing dissimilar: 1000

In [135]:
# pair dataset creation of movies
import torch
from torch.utils.data import Dataset

class MoviePairDataset(Dataset):

    def __init__(self, pairs, labels, vectors):
        self.pairs = pairs
        self.labels = labels
        self.vectors = vectors

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        # getting the movies indices
        movie_a_idx, movie_b_idx = self.pairs[idx]
     # retirveing movie pca vectors
        movie_a = self.vectors[movie_a_idx]
        movie_b = self.vectors[movie_b_idx]
# getting similarity labels
        label = self.labels[idx]

        return movie_a, movie_b, label

train_dataset = MoviePairDataset(
    train_pairs,
    train_labels,
    vectors_pca
)

test_dataset = MoviePairDataset(
    test_pairs,
    test_labels,
    vectors_pca
)

movie_a, movie_b, label = train_dataset[0]

print("Movie A shape:", movie_a.shape)
print("Movie B shape:", movie_b.shape)
print("Label:", label)

Movie A shape: (1000,)
Movie B shape: (1000,)
Label: 0

In [137]:
# Dataset loader

from torch.utils.data import DataLoader

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

movie_a, movie_b, batch_labels = next(iter(train_loader))

print("Movie A batch:", movie_a.shape)
print("Movie B batch:", movie_b.shape)
print("Labels batch:", batch_labels.shape)

Movie A batch: torch.Size([32, 1000])
Movie B batch: torch.Size([32, 1000])
Labels batch: torch.Size([32])

In [138]:
# creation of recomendationNN
import torch 
import torch.nn as nn
class RecommendationNN(nn.Module):
    def __init__(self,in_features,hidden1,hidden2,hidden3,out_features):
        super().__init__()
        self.fc1=nn.Linear(in_features,hidden1)
        self.relu= nn.ReLU()
        self.fc2=nn.Linear(hidden1,hidden2)
        self.fc3=nn.Linear(hidden2,hidden3)
        self.fc4=nn.Linear(hidden3,out_features)

    def forward(self,x):
        x= self.fc1(x)
        x= self.relu(x)
        
        x=self.fc2(x)
        x=self.relu(x)
        
        x= self.fc3(x)
        x= self.relu(x)
        x=self.fc4(x)

        return x

model = RecommendationNN(
    in_features=1000,
    hidden1=512,
    hidden2=256,
    hidden3=128,
    out_features=64)

#cosine embedding loss (loss for our nn)
criterion = torch.nn.CosineEmbeddingLoss()

# NAG optimizers 
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.001,
    momentum=0.9,
    nesterov=True
)


# RecommendationNN training

# Number of epochs
epochs = 10

for epoch in range(epochs):

    model.train()
    total_loss = 0

    for movie_a, movie_b, labels in train_loader:

        # Convert labels: 0 → -1, 1 → 1
        # for our cosine embedding
        loss_labels = labels.float() * 2 - 1

        # Forward pass
        embedding_a = model(movie_a)
        embedding_b = model(movie_b)

        # Calculate loss
        loss = criterion(
            embedding_a,
            embedding_b,
            loss_labels
        )

        # Clear old gradients
        optimizer.zero_grad()

        # Backpropagation
        loss.backward()

        # Update NN weights using NAG
        optimizer.step()

        # Add batch loss
        total_loss += loss.item()

    # Calculate average loss for this epoch
    average_loss = total_loss / len(train_loader)

    print("Epoch:", epoch + 1)
    print("Average Training Loss:", average_loss)

print("Training completed")

Epoch: 1
Average Training Loss: 0.49355121719837186
Epoch: 2
Average Training Loss: 0.0656560618430376
Epoch: 3
Average Training Loss: 0.008404398953542114
Epoch: 4
Average Training Loss: 0.0065417822506278756
Epoch: 5
Average Training Loss: 0.005668920936994255
Epoch: 6
Average Training Loss: 0.00510811345744878
Epoch: 7
Average Training Loss: 0.0047166280560195445
Epoch: 8
Average Training Loss: 0.004421666969079524
Epoch: 9
Average Training Loss: 0.004191958663519472
Epoch: 10
Average Training Loss: 0.0040248149386607115
Training completed

In [139]:
# RecommendationNN testing

model.eval()

total_test_loss = 0

with torch.no_grad():

    for movie_a, movie_b, labels in test_loader:

        # Convert labels: 0 → -1, 1 → 1
        loss_labels = labels.float() * 2 - 1

        # Forward pass
        embedding_a = model(movie_a)
        embedding_b = model(movie_b)

        # Calculate cosine loss
        loss = criterion(
            embedding_a,
            embedding_b,
            loss_labels
        )

        # Add test loss
        total_test_loss += loss.item()
         


# Calculate average test loss
average_test_loss = total_test_loss / len(test_loader)

print("Epoch:", epoch + 1)
print("Average Testing Loss:", average_test_loss)
print("Testing completed")

Epoch: 10
Average Testing Loss: 0.0027268787121607196
Testing completed

In [142]:
# Generating embeddings for all movies

model.eval()

with torch.no_grad():

    all_vectors = torch.tensor(
        vectors_pca,
        dtype=torch.float32
    )

    movie_embeddings = model(all_vectors)

print("Movie embeddings shape:", movie_embeddings.shape)

Movie embeddings shape: torch.Size([7789, 64])

In [145]:
# Main part of RecommendationNN where we interact

import torch
import torch.nn.functional as F

# Evaluation mode
model.eval()


movie_name = input("Enter a movie you like: ")


# Find the movie in dataset
matches = dataset[
    dataset["Title"].str.lower() == movie_name.lower()
]


if len(matches) == 0:

    print("Movie not found.")


else:

    # Getting movie index
    movie_index = matches.index[0]

    # Selecting movie embedding
    selected_embedding = movie_embeddings[movie_index]


    # Calculate cosine similarity with all movies
    similarities = F.cosine_similarity(
        selected_embedding.unsqueeze(0),
        movie_embeddings
    )


    # Sorting movies by similarity
    top_indices = torch.argsort(
        similarities,
        descending=True
    )


    print("\nRecommended Movies:")

    count = 0

    for index in top_indices:

        index = index.item()

        # Skip the selected movie itself
        if index == movie_index:
            continue

        print(
            dataset.loc[index, "Title"],
            "→ Similarity:",
            round(similarities[index].item(), 4)
        )

        count += 1

        if count == 5:
            break

Enter a movie you like:  3 Generations

Recommended Movies:
The Love Affair → Similarity: 0.999
Rattlesnake → Similarity: 0.9989
The Bulbul's Nest → Similarity: 0.9989
The Arbitration → Similarity: 0.9989
Clair Obscur → Similarity: 0.9989

In [146]:
# Checking embedding similarity distribution

similarities = F.cosine_similarity(
    movie_embeddings[:-1],
    movie_embeddings[1:]
)

print("Average embedding similarity:", similarities.mean().item())
print("Minimum embedding similarity:", similarities.min().item())
print("Maximum embedding similarity:", similarities.max().item())

Average embedding similarity: 0.5703283548355103
Minimum embedding similarity: -0.19823624193668365
Maximum embedding similarity: 1.0000001192092896

In [103]:
print(dataset.Title.head(100))

0                 3%
1              07:19
2              23:59
3                  9
4                 21
           ...
95          28 Moons
96    3 Days to Kill
97       3 Deewarein
98     3 Generations
99        3 Heroines
Name: Title, Length: 100, dtype: object

In [88]:
#dataset api configuration
import os
import shutil

source = os.path.expanduser("~/Downloads/kaggle.json")
destination_folder = os.path.expanduser("~/.kaggle")
destination = os.path.join(destination_folder, "kaggle.json")

os.makedirs(destination_folder, exist_ok=True)

shutil.copy(source, destination)

print("Kaggle API configured successfully!")

Kaggle API configured successfully!